---
title: "temporal"
author: "Allie Cole, Felicia Cruz, Charles Hendrickson, Jake Eisaguirre"
date: "3/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libraries 
```{r}
library(tidyverse)
library(ggplot2)
library(here)
library(janitor)
library(lubridate)
library(stringr)
library(plotly)
library(patchwork)
 
```


# COT
```{r}
# read in data
cots <- read_csv(here("data/csv/COT_abundance.csv")) %>%
  clean_names()

# cots$year <- as.factor(cots$year)
# summary df
cots_summary <- cots %>%
  mutate(year = as.numeric(year)) %>% 
  group_by(site, year, habitat) %>%
  summarize(cot_raw_count = sum(cots))



# DENSITY PLOT
# densities by site
# group by site & year , sum total observations / 1000 -> annual site density
# 4 5x50 m transects per site

cots_density <-  cots %>%
  group_by(site, year, habitat) %>%
  summarize(density = (sum(cots)/1000)) # this should give annual site density/ m^2

cots_density$habitat <- str_replace(cots_density$habitat, "Fringing Reef", "Fringing")

ggplot(data = cots_density, aes(x = year, y = density)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  facet_wrap(~site) +
  labs(title = 'Crown of Thorns Sea Stars - Annual Site Densities',
       subtitle = 'Moorea, French Polynesia (2005 - 2018)',
       y = 'Density (count/m^2)',
       x = 'Year',
       color = 'Site') +
  #scale_x_discrete(labels = c(“”, 2006, “”, 2008, “”, 2010, “”, 2012, “”, 2014, “”, 2016, “”, 2018)) +
  scale_color_manual(values = c('#40B5AD', '#87CEEB', '#4682B4', '#6F8FAF', '#9FE2BF', '#6495ED')) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title.x = element_text(size=14),
        axis.title.y = element_text(size = 14),
        plot.title = element_text(size = 16))
```

# percent coral cover - Double check coral species list
```{r}

coral_cover_raw <- read_csv(here("data", "csv", "percent_coral_cover.csv")) %>%
  clean_names()


coral_cover <- coral_cover_raw %>%
  as.data.frame() %>% 
  select(date, site, taxonomy_substrate_or_functional_group, percent_cover, habitat) %>% 
  filter(!str_detect(percent_cover, "ND")) %>% 
  filter(!str_detect(percent_cover, "0.0")) %>% 
  filter(!taxonomy_substrate_or_functional_group %in% 
           c("Sand", "Non-coralline Crustose Algae", "Unknown or Other",
             "CTB", "Macroalgae")) %>% 
  mutate(date = str_sub(date, 1, -4)) %>% 
  mutate(date = as.numeric(date),
         percent_cover = as.numeric(percent_cover))

coral_cover$habitat <- str_replace(coral_cover$habitat, "Outer 17", "Forereef")
coral_cover$habitat <- str_replace(coral_cover$habitat, "Outer 10", "Forereef")
coral_cover$taxonomy_substrate_or_functional_group <- str_replace(coral_cover$taxonomy_substrate_or_functional_group, "Porites spp. Massive", "Porites")
coral_cover$taxonomy_substrate_or_functional_group <- str_replace(coral_cover$taxonomy_substrate_or_functional_group, "Porites rus", "Porites")
coral_cover$taxonomy_substrate_or_functional_group <- str_replace(coral_cover$taxonomy_substrate_or_functional_group, "Porites irregularis", "Porites")


coral_corals <- coral_cover %>% 
  filter(taxonomy_substrate_or_functional_group %in% c("Porites", "Acropora", "Pocillopora"))


sum_coral_cover <- coral_cover %>%
  mutate(year = date) %>% 
  group_by(site, year, habitat) %>% 
  summarize(mean_coral_cover = (mean(percent_cover)))

sum_trophic_corals <- coral_corals %>% 
  mutate(year = date) %>% 
  group_by(site, year, habitat, taxonomy_substrate_or_functional_group) %>% 
  summarize(mean_coral_cover = (mean(percent_cover)))
  
  
  
ggplot(sum_coral_cover) +
  geom_line(aes(x = year, y = mean_coral_cover, group = site, color = site)) +
  xlab("Year") +
  ylab(expression(paste("Average Percent Coral Cover per 0.25 ", m^{2}))) +
  theme_classic()
```

# herbivore biomass
```{r}
# read in data and clean
fish_biomass <- read_csv(here("data/csv/fish.csv")) %>%
  clean_names()

fish_biomass$site <- as.factor(fish_biomass$site)
# We only want “LTER #”
# Below I used substr() function to find first n characters of the column in R. substr() function takes column name, starting position and length of the strings as argument, which will return the substring of the specific column as shown below.

fish_biomass$substring_location =
  substr(fish_biomass$location,1,6)
# Create ‘year’, ‘site’, and ‘biomass’ column
biomass_summary <- fish_biomass %>%
  filter(coarse_trophic == "Primary Consumer") %>%
  select(year, "site" = substring_location, biomass, habitat) %>%
  mutate(year = as.numeric(year)) %>% 
  group_by(year, site, habitat) %>%
  summarize(mean_biomass_p_consumers = (mean(biomass)/1000)) #5 x 50 meter transect * 4 = 1000 total meters

biomass_summary$habitat <- str_replace(biomass_summary$habitat, "BA", "Backreef")
biomass_summary$habitat <- str_replace(biomass_summary$habitat, "FO", "Forereef")
biomass_summary$habitat <- str_replace(biomass_summary$habitat, "FR", "Fringing")


ggplot(data = biomass_summary, aes(x = year, y = mean_biomass_p_consumers)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site))
```

# percent algae version 1
```{r}
# algae_cover_raw <- read_csv(here("data", "csv", "percent_algae_cover.csv")) %>%
#   clean_names()
# 
# algae_cover <- algae_cover_raw %>% 
#   select(year, site, taxonomy_substrate_functional_group, percent_cover, habitat) %>% 
#   filter(!taxonomy_substrate_functional_group %in% 
#            c("Sand", "Coral", "Bare Space", "Millepora platyphylla", "Soft Coral",
#              "No data", "NA", "Sponge", "Shell Debris", "Coral Rubble")) %>% 
#   filter(!str_detect(percent_cover, "0"))
#   
# algae_cover$habitat <- str_replace(algae_cover$habitat, "Outer 17", "Forereef")
# algae_cover$habitat <- str_replace(algae_cover$habitat, "Outer 10", "Forereef")
# 
# sum_algae_cover <- algae_cover %>% 
#   mutate(year = as.numeric(year)) %>% 
#   group_by(year, site, habitat) %>% 
#   summarize(mean_algae_cover = mean(percent_cover))
# 
# ggplot(sum_algae_cover) +
#   geom_line(aes(x = year, y = mean_algae_cover, group = site, color = site)) +
#   xlab("Year") +
#   ylab(expression(paste("Average Percent Algae Cover per 0.25 ", m^{2}))) +
#   theme_classic()

```

# updated algae subset and plot 
```{r}
# wrangle using coral_cover framework, filter for "macroalgae" 
algae_cover <- coral_cover_raw %>%
  as.data.frame() %>% 
  select(date, site, taxonomy_substrate_or_functional_group, percent_cover, habitat) %>% 
  filter(taxonomy_substrate_or_functional_group == "Macroalgae") %>% 
  filter(!str_detect(percent_cover, "ND")) %>%
  filter(!str_detect(percent_cover, "0.0")) %>%
  mutate(date = str_sub(date, 1, -4)) %>%
  mutate(date = as.numeric(date),
         percent_cover = as.numeric(percent_cover))

algae_cover$habitat <- str_replace(algae_cover$habitat, "Outer 17", "Forereef")
algae_cover$habitat <- str_replace(algae_cover$habitat, "Outer 10", "Forereef")


sum_algae_cover <- algae_cover %>%
  mutate(year = date) %>% # rename date to year 
  group_by(site, year, habitat) %>% 
  summarize(mean_algae_cover = (mean(percent_cover)))
```



# join data sets on site, and year
```{r}

sum_corals <- read_csv(here("data", "csv", "sum_trophic_corals.csv"))
temp <- read_csv(here("data/csv/temporal_data_joined.csv"))

algae_coral <- left_join(sum_coral_cover, sum_algae_cover, on = c(year, site, habitat))
ag_c <- left_join(algae_coral, cots_density, on = c(year,site, habitat))

temporal_data <- left_join(ag_c, biomass_summary, on = c(year,site, habitat)) %>% 
  rename(cots_density = density)

sum_coral <- pivot_wider(sum_corals, names_from = taxonomy_substrate_or_functional_group, values_from = mean_coral_cover ) %>% 
  group_by(site, year, habitat)

temporal_d <- temp %>% 
  dplyr::select(!c(1)) %>% 
  left_join(sum_coral, on = c(year, site, habitat)) %>% 
  dplyr::select(!c(8))


# make new csv to easily source in the shiny app 
write.csv(temporal_d, here("data/csv/temporal_data.csv")) 

#trohpic group corals
write.csv(sum_trophic_corals, here("data", "csv", "sum_trophic_corals.csv"))
```

using the joined df to make a faceted plot based on variable choice (4 plots to be included on app)
```{r}
# cots 
ggplot(data = temporal_data, aes(x = year, y = cots_density)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  facet_wrap(~site) +
  labs(title = 'Crown of Thorns Sea Stars - Annual Site Densities',
       subtitle = 'Moorea, French Polynesia (2005 - 2018)',
       y = expression(paste("Density (count per ", m^{2}, ")")),
       x = 'Year',
       color = 'Site') +
  scale_color_manual(values = c('#40B5AD', '#87CEEB', '#4682B4', '#6F8FAF', '#9FE2BF', '#6495ED')) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title.x = element_text(size=14),
        axis.title.y = element_text(size = 14),
        plot.title = element_text(size = 16))


# mean coral cover 
ggplot(data = temporal_data, aes(x = year, y = mean_coral_cover)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  facet_wrap(~site) +
  labs(title = 'Mean Coral Cover',
       subtitle = 'Moorea, French Polynesia (2005 - 2021)',
       y = expression(paste("Average Percent Coral Cover per 0.25 ", m^{2})),
       x = 'Year',
       color = 'Site') +
  scale_color_manual(values = c('#40B5AD', '#87CEEB', '#4682B4', '#6F8FAF', '#9FE2BF', '#6495ED')) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title.x = element_text(size=14),
        axis.title.y = element_text(size = 14),
        plot.title = element_text(size = 16))

# mean algae cover 
ggplot(data = temporal_data, aes(x = year, y = mean_algae_cover)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  facet_wrap(~site) +
  labs(title = 'Mean Algae Cover',
       subtitle = 'Moorea, French Polynesia (2005 - 2021)',
       y = expression(paste("Average Percent Algae Cover per 0.25 ", m^{2})),
       x = 'Year',
       color = 'Site') +
  scale_color_manual(values = c('#40B5AD', '#87CEEB', '#4682B4', '#6F8FAF', '#9FE2BF', '#6495ED')) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title.x = element_text(size=14),
        axis.title.y = element_text(size = 14),
        plot.title = element_text(size = 16))

# fish biomass 
# no data for 2005
ggplot(data = temporal_data, aes(x = year, y = mean_biomass_p_consumers)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  facet_wrap(~site) +
  labs(title = 'Mean Fish Biomass (Primary Consumers)',
       subtitle = 'Moorea, French Polynesia (2006 - 2021)',
       x = 'Year',
       color = 'Site') +
  scale_color_manual(values = c('#40B5AD', '#87CEEB', '#4682B4', '#6F8FAF', '#9FE2BF', '#6495ED')) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title.x = element_text(size=14),
        axis.title.y = element_text(size = 14),
        plot.title = element_text(size = 16))
```


Patchwork plot for all 4 variables for a user's chosen LTER site 
```{r}
coral_plot <- ggplot(data = temporal_data, aes(x = year, y = mean_coral_cover)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  labs(x = "Year",
       y = expression(atop("Mean Coral Cover", paste(paste("(% per 0.25 ", m^{2}, ")"))))) 

cots_plot <- ggplot(data = temporal_data, aes(x = year, y = cots_density)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  labs(x = "Year",
       y = expression(atop("COTS Density", paste(paste("(Count per ", m^{2}, ")")))))
        
biomass_plot <- ggplot(data = temporal_data, aes(x = year, y = mean_biomass_p_consumers)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  labs(x = "Year",
       y = expression(atop("Mean Fish Biomass", paste(paste("(% per 0.25 ", m^{2}, ")"))))) # need to check these units

algae_plot <- ggplot(data = temporal_data, aes(x = year, y = mean_algae_cover)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  labs(x = "Year",
       y = expression(atop("Mean Algae Cover", paste(paste("(% per 0.25", m^{2}, ")")))))

temporal_patchwork <- coral_plot/cots_plot/biomass_plot/algae_plot +
  plot_layout(guides = 'collect') 
  # plot_layout(heights = unit(c(5, 5, 5, 5), c('cm', 'null')))# combines the legends 

temporal_patchwork
```

# trying to get a two line y axis 
```{r}
ggplot(data = temporal_data, aes(x = year, y = mean_algae_cover)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  labs(x = "Year",
       y = expression(atop("Mean Algae Cover", paste(paste("(% per ", m^{2}, ")")))))
```

